spring:
       datasource:
            name: ztm
            url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=gbk&autoReconnect=true&allowMultiQueries=true
            username: root
            password: 123456
            driver-class-name: com.mysql.jdbc.Driver
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x' FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
        
mybatis:
        mapperLocations: classpath*:com/gwg/demo/mapper/*.xml
        typeAliasesPackage: com.gwg.demo.model
       